require('../config/env');
const { pool } = require('../config/database');
const logger = require('../config/logger');

const topics = [
  // === BASIC PHASE 1: FOUNDATIONS ===
  { name: 'Time & Space Complexity', slug: 'time-space-complexity', tier: 'Basic', order_in_sequence: 1, simple_definition: 'Complexity analysis measures how your algorithm\'s runtime and memory grow as input size increases. O(n) means linear, O(n²) means quadratic. This determines if your code works for 100 items or 1 billion.', difficulty_rating: 1.0, estimated_hours: 3, prerequisites: [], reference_url: 'https://www.geeksforgeeks.org/analysis-of-algorithms-set-1-asymptotic-analysis/', youtube_search_query: 'Big O notation time space complexity', real_world_uses: { examples: [{ company: 'Netflix', use_case: 'Recommendation algorithm performance', explanation: 'Must return recommendations in O(log n) for millions of users. O(n²) would be too slow.' }, { company: 'Google', use_case: 'Search index lookup', explanation: 'With 8 billion webpages, search must be O(log n) or faster. Understanding complexity lets them serve results in milliseconds.' }] } },
  { name: 'Arrays - 1D', slug: 'arrays-1d', tier: 'Basic', order_in_sequence: 2, simple_definition: 'Arrays store multiple items in a line. Access any item instantly by position (index) in O(1) time. Like numbered boxes where you can grab box #5 directly without checking boxes 1–4.', difficulty_rating: 1.5, estimated_hours: 4, prerequisites: ['Time & Space Complexity'], reference_url: 'https://www.geeksforgeeks.org/array-data-structure/', youtube_search_query: 'Array data structure basics tutorial', real_world_uses: { examples: [{ company: 'Instagram', use_case: 'Reel feed buffering', explanation: 'Reels are stored in an array. Scroll down = array[index++]. Instant O(1) access.' }, { company: 'Spotify', use_case: 'Playlist storage and shuffle', explanation: 'Your playlist is an array of songs. Shuffle randomizes the array. Next song is array[currentIndex + 1].' }, { company: 'Netflix', use_case: 'Video quality buffer', explanation: 'Video chunks are stored in an array buffer for smooth playback.' }] } },
  { name: 'Strings', slug: 'strings', tier: 'Basic', order_in_sequence: 3, simple_definition: 'Strings are sequences of characters — like arrays of letters. You can search, replace, split, and reverse them. Text editors and search engines are built on string algorithms.', difficulty_rating: 1.5, estimated_hours: 4, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/string-data-structure/', youtube_search_query: 'String data structure manipulation', real_world_uses: { examples: [{ company: 'VS Code', use_case: 'Find & replace', explanation: 'Ctrl+H searches for substrings using KMP or regex. Instant search in 10,000+ line files.' }, { company: 'Gmail', use_case: 'Email search and filtering', explanation: 'Search "from:boss subject:meeting" requires parsing and pattern matching on email strings.' }] } },
  { name: 'Recursion Basics', slug: 'recursion-basics', tier: 'Basic', order_in_sequence: 4, simple_definition: 'Recursion is a function calling itself to solve smaller versions of the same problem. Break big problems into tiny pieces until you hit a base case you can solve directly, then combine answers.', difficulty_rating: 2.2, estimated_hours: 4, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/recursion/', youtube_search_query: 'Recursion explained simple example', real_world_uses: { examples: [{ company: 'File Explorer', use_case: 'Find all files in nested folders', explanation: 'Recursively searches each subfolder level. No loops needed.' }, { company: 'JSON parsers', use_case: 'Parsing nested structures', explanation: 'JSON can have objects inside objects. Recursion handles unlimited nesting elegantly.' }] } },

  // === BASIC PHASE 2: DATA STRUCTURES ===
  { name: '2D Arrays', slug: '2d-arrays', tier: 'Basic', order_in_sequence: 5, simple_definition: '2D arrays are grids — rows and columns. Think of a spreadsheet or chessboard. Access element at row i, column j instantly with array[i][j].', difficulty_rating: 1.8, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/multidimensional-arrays-in-c-cpp/', youtube_search_query: '2D array matrix tutorial', real_world_uses: { examples: [{ company: 'Adobe Photoshop', use_case: 'Image pixel manipulation', explanation: 'An image is a 2D array: pixels[row][col]. Filters apply operations across all pixels.' }, { company: 'Chess.com', use_case: 'Game board representation', explanation: '8×8 board = 2D array. board[row][col] = piece at that square.' }] } },
  { name: 'Stacks', slug: 'stacks', tier: 'Basic', order_in_sequence: 6, simple_definition: 'Stacks are LIFO (Last In, First Out). Like a stack of plates — add on top (push), remove from top (pop). Last plate added is first plate removed.', difficulty_rating: 1.8, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/stack-data-structure-and-algorithms/', youtube_search_query: 'Stack data structure LIFO push pop', real_world_uses: { examples: [{ company: 'Web Browsers', use_case: 'Back button navigation', explanation: 'Every page visited is pushed onto a stack. Click back = pop current page.' }, { company: 'Code Debuggers', use_case: 'Call stack visualization', explanation: 'Function A calls B calls C — they stack. Debugger shows stack trace: C → B → A.' }] } },
  { name: 'Queues', slug: 'queues', tier: 'Basic', order_in_sequence: 7, simple_definition: 'Queues are FIFO (First In, First Out). Like a movie theater line — first person in line gets served first. Items enter back, leave front.', difficulty_rating: 1.8, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/queue-data-structure/', youtube_search_query: 'Queue data structure FIFO enqueue dequeue', real_world_uses: { examples: [{ company: 'Uber/Lyft', use_case: 'Ride request handling', explanation: 'Ride requests queue up. When driver is available, they take the oldest request — fair FIFO.' }, { company: 'Printer', use_case: 'Print job queue', explanation: 'Print jobs queue on your computer. Printer processes them in order sent.' }] } },
  { name: 'Linked Lists', slug: 'linked-lists', tier: 'Basic', order_in_sequence: 8, simple_definition: 'Linked lists are chains of connected nodes. Each node holds data and points to the next node. Unlike arrays, they\'re spread in memory and connected by pointers.', difficulty_rating: 2.5, estimated_hours: 5, prerequisites: ['Arrays - 1D', 'Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/data-structures/linked-list/', youtube_search_query: 'Linked list data structure node pointer', real_world_uses: { examples: [{ company: 'Browser', use_case: 'Back/Forward history', explanation: 'Browser history is a doubly-linked list. Each page points to previous (back) and next (forward).' }, { company: 'Spotify', use_case: 'Playlist navigation', explanation: 'Playlist is a linked list. Navigate forward AND backward instantly.' }] } },
  { name: 'Hash Maps / Hash Tables', slug: 'hash-maps', tier: 'Basic', order_in_sequence: 9, simple_definition: 'Hash maps are like phone contact lists. Instead of scanning all names, you jump directly to the name using a hash function. Key → Value lookup in O(1) average time.', difficulty_rating: 2.0, estimated_hours: 4, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/hashing-set-1-introduction/', youtube_search_query: 'Hash map hash table collision chaining', real_world_uses: { examples: [{ company: 'Any login system', use_case: 'User lookup by email', explanation: 'Millions of users. Hash map: email → userID. Instant login, no scanning.' }, { company: 'Redis Cache', use_case: 'In-memory caching', explanation: 'Store key-value pairs. Instant retrieval instead of database query.' }, { company: 'bit.ly', use_case: 'URL shortening', explanation: 'shortCode → longURL in a hash map. Clicking short link instantly retrieves the real URL.' }] } },
  { name: 'Sets & HashSets', slug: 'sets-hashsets', tier: 'Basic', order_in_sequence: 10, simple_definition: 'Sets are collections with no duplicates. HashSets use a hash map internally for O(1) membership checking. Ask "is X in this set?" in constant time.', difficulty_rating: 1.8, estimated_hours: 3, prerequisites: ['Hash Maps / Hash Tables'], reference_url: 'https://www.geeksforgeeks.org/hashing-set-2-separate-chaining/', youtube_search_query: 'HashSet no duplicates membership', real_world_uses: { examples: [{ company: 'Email apps', use_case: 'Duplicate contact removal', explanation: 'AddressBook uses set to ensure no duplicate contacts.' }, { company: 'Spell Checker', use_case: 'Valid word checking', explanation: 'Dictionary stored as set. Check if typed word is valid: is_valid = word in dictionary_set.' }] } },

  // === BASIC PHASE 3: SEARCHING & SORTING ===
  { name: 'Linear Search', slug: 'linear-search', tier: 'Basic', order_in_sequence: 11, simple_definition: 'Linear search checks items one by one until you find the target. O(n) time. Simple but slow for large datasets.', difficulty_rating: 1.0, estimated_hours: 2, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/linear-search/', youtube_search_query: 'Linear search sequential search', real_world_uses: { examples: [{ company: 'Small apps', use_case: 'Finding element in small list', explanation: 'For <100 items, linear search is perfectly fine and easy to code.' }] } },
  { name: 'Binary Search', slug: 'binary-search', tier: 'Basic', order_in_sequence: 12, simple_definition: 'Binary search cuts the search space in half each time. Finds elements in O(log n). Requires sorted data but way faster than linear for large datasets.', difficulty_rating: 1.5, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/binary-search/', youtube_search_query: 'Binary search algorithm explained', real_world_uses: { examples: [{ company: 'Google Search', use_case: 'Finding pages in sorted index', explanation: 'Index of 8 billion pages is sorted. Binary search finds your query in ~33 steps.' }, { company: 'Git', use_case: 'git bisect — finding broken commit', explanation: 'git bisect uses binary search to find which commit introduced a bug in O(log n) commits.' }] } },
  { name: 'Sorting — Bubble, Selection, Insertion', slug: 'sorting-basic', tier: 'Basic', order_in_sequence: 13, simple_definition: 'Basic O(n²) sorting algorithms. Bubble: swap adjacent pairs. Selection: find minimum, move to front. Insertion: build sorted array one item at a time. Slow but important to understand.', difficulty_rating: 1.8, estimated_hours: 4, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/sorting-algorithms/', youtube_search_query: 'Bubble sort selection sort insertion sort explained', real_world_uses: { examples: [{ company: 'Small datasets', use_case: 'Sorting under 10,000 items', explanation: 'For small data, simple O(n²) sorts are fast enough and easy to implement.' }] } },
  { name: 'Sorting — Merge & Quick Sort', slug: 'sorting-advanced', tier: 'Basic', order_in_sequence: 14, simple_definition: 'Efficient sorting algorithms. Merge sort: divide & conquer, O(n log n) guaranteed. Quick sort: usually O(n log n). Production databases and runtimes use these.', difficulty_rating: 2.5, estimated_hours: 6, prerequisites: ['Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/merge-sort/', youtube_search_query: 'Merge sort quick sort divide conquer', real_world_uses: { examples: [{ company: 'Database systems', use_case: 'Sorting large result sets', explanation: 'PostgreSQL/MySQL use merge sort for external sorting. O(n log n) handles millions of rows.' }, { company: 'Java / Python', use_case: 'Built-in sort()', explanation: 'Java Arrays.sort() uses TimSort (merge + insertion hybrid). O(n log n) for 100M+ items.' }] } },

  // === BASIC PHASE 4: TREES ===
  { name: 'Binary Trees Basics', slug: 'binary-trees-basics', tier: 'Basic', order_in_sequence: 15, simple_definition: 'Binary trees have nodes with 0, 1, or 2 children. Root at top, leaves at bottom. Used for hierarchical data representation.', difficulty_rating: 2.5, estimated_hours: 5, prerequisites: ['Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/binary-tree-data-structure/', youtube_search_query: 'Binary tree data structure root leaves', real_world_uses: { examples: [{ company: 'Browser DOM', use_case: 'HTML element hierarchy', explanation: '<html> is root, <body> is child. CSS selectors traverse this tree.' }, { company: 'File systems', use_case: 'Directory structure', explanation: 'Root directory → subfolders → files. Tree organizes everything hierarchically.' }] } },
  { name: 'Binary Search Trees (BST)', slug: 'binary-search-trees', tier: 'Basic', order_in_sequence: 16, simple_definition: 'BSTs maintain sorted order: left child < parent < right child. Enables O(log n) search, insert, delete when balanced. Foundation for database indexing.', difficulty_rating: 2.8, estimated_hours: 6, prerequisites: ['Binary Trees Basics'], reference_url: 'https://www.geeksforgeeks.org/binary-search-tree-data-structure/', youtube_search_query: 'Binary search tree BST insert search delete', real_world_uses: { examples: [{ company: 'Databases', use_case: 'B-tree index lookup', explanation: 'Database indexes use B-trees (BST generalization). Find any row in millions instantly.' }] } },
  { name: 'Tree Traversal', slug: 'tree-traversal', tier: 'Basic', order_in_sequence: 17, simple_definition: 'Three ways to visit all nodes: Inorder (left-root-right), Preorder (root-left-right), Postorder (left-right-root). Each traversal solves different problems.', difficulty_rating: 2.3, estimated_hours: 4, prerequisites: ['Binary Trees Basics', 'Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-postorder/', youtube_search_query: 'Inorder preorder postorder tree traversal', real_world_uses: { examples: [{ company: 'XML/JSON parsers', use_case: 'Visiting all nodes in order', explanation: 'Traversal visits each element to extract data or validate structure.' }] } },

  // === BASIC PHASE 5: GRAPHS ===
  { name: 'Graph Basics & Representation', slug: 'graph-basics', tier: 'Basic', order_in_sequence: 18, simple_definition: 'Graphs are networks of nodes connected by edges. Social networks, maps, webpages — all graphs. Store as adjacency list (sparse) or matrix (dense).', difficulty_rating: 2.0, estimated_hours: 4, prerequisites: ['Linked Lists'], reference_url: 'https://www.geeksforgeeks.org/graph-and-its-representations/', youtube_search_query: 'Graph data structure adjacency list matrix', real_world_uses: { examples: [{ company: 'Facebook/LinkedIn', use_case: 'Social network', explanation: 'People are nodes, friendships are edges. Graph represents the entire social network.' }, { company: 'Google Maps', use_case: 'Road network', explanation: 'Cities are nodes, roads are edges. Graph represents the entire transportation network.' }] } },
  { name: 'Graph Traversal — BFS', slug: 'graph-traversal-bfs', tier: 'Basic', order_in_sequence: 19, simple_definition: 'BFS explores a graph level by level using a queue. Finds shortest path in unweighted graphs. Visits all level-1 neighbors first, then level-2, etc.', difficulty_rating: 2.2, estimated_hours: 4, prerequisites: ['Graph Basics & Representation', 'Queues'], reference_url: 'https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/', youtube_search_query: 'BFS breadth first search queue', real_world_uses: { examples: [{ company: 'Facebook', use_case: 'Friend recommendations', explanation: 'BFS from you finds friends (level 1), friends-of-friends (level 2). Recommends closest connections.' }] } },
  { name: 'Graph Traversal — DFS', slug: 'graph-traversal-dfs', tier: 'Basic', order_in_sequence: 20, simple_definition: 'DFS explores a graph depth-first using a stack or recursion. Goes deep into one branch before backtracking. Detects cycles and connected components.', difficulty_rating: 2.2, estimated_hours: 4, prerequisites: ['Graph Basics & Representation', 'Stacks', 'Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/', youtube_search_query: 'DFS depth first search recursion stack', real_world_uses: { examples: [{ company: 'Compiler', use_case: 'Circular dependency detection', explanation: 'DFS detects if modules form a cycle: A imports B imports C imports A — invalid!' }, { company: 'Game engines', use_case: 'Maze solving', explanation: 'DFS explores maze paths, backtracks at dead ends, finds the exit.' }] } },
  { name: "Dijkstra's Algorithm", slug: 'dijkstra-algorithm', tier: 'Basic', order_in_sequence: 21, simple_definition: "Dijkstra finds the shortest path from source to all nodes in O((V + E) log V). Uses a priority queue to always explore the closest unvisited node next.", difficulty_rating: 3.0, estimated_hours: 6, prerequisites: ['Graph Basics & Representation', 'Graph Traversal — BFS'], reference_url: 'https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/', youtube_search_query: 'Dijkstra algorithm shortest path priority queue', real_world_uses: { examples: [{ company: 'Google Maps', use_case: 'Fastest route navigation', explanation: "Dijkstra finds shortest path from your location to destination, weighing roads by travel time." }, { company: 'Network routing', use_case: 'OSPF packet routing', explanation: 'Routers use Dijkstra to find the fastest path to send packets across the internet.' }] } },

  // === BASIC PHASE 6: ADVANCED TECHNIQUES ===
  { name: 'Heaps & Priority Queues', slug: 'heaps-priority-queues', tier: 'Basic', order_in_sequence: 22, simple_definition: 'Heaps maintain a partial order: parent ≤ children (min-heap) or parent ≥ children (max-heap). Priority queue uses a heap to return the highest-priority element first in O(log n).', difficulty_rating: 2.5, estimated_hours: 5, prerequisites: ['Binary Trees Basics', 'Queues'], reference_url: 'https://www.geeksforgeeks.org/binary-heap/', youtube_search_query: 'Heap data structure min heap max heap', real_world_uses: { examples: [{ company: 'OS Task Scheduler', use_case: 'Process priority scheduling', explanation: 'Heap stores processes by priority. OS always runs the highest-priority process next.' }] } },
  { name: 'Prefix Sum & Range Queries', slug: 'prefix-sum', tier: 'Basic', order_in_sequence: 23, simple_definition: 'Prefix sum stores cumulative totals: prefix[i] = sum of all elements up to index i. Enables O(1) range sum queries: sum(L, R) = prefix[R] − prefix[L−1].', difficulty_rating: 1.5, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications-in-competitive-programming/', youtube_search_query: 'Prefix sum array range query', real_world_uses: { examples: [{ company: 'Database analytics', use_case: 'Fast range aggregate queries', explanation: '"Sum sales from Jan 15 to Feb 20" is O(1) with prefix sums instead of O(n).' }] } },
  { name: 'Two Pointers Technique', slug: 'two-pointers', tier: 'Basic', order_in_sequence: 24, simple_definition: 'Use two pointers moving at different speeds or from different ends. Check palindromes (left & right), find pairs summing to target. Elegant O(n) solutions without extra space.', difficulty_rating: 1.8, estimated_hours: 3, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/two-pointers-technique/', youtube_search_query: 'Two pointers technique array', real_world_uses: { examples: [{ company: 'Interview problems', use_case: 'Optimize brute force to O(n)', explanation: '"Two Sum": instead of O(n²) nested loops, two pointers solve it in O(n).' }] } },
  { name: 'Sliding Window', slug: 'sliding-window', tier: 'Basic', order_in_sequence: 25, simple_definition: 'Maintain a window of fixed or variable size sliding across an array. Calculate result for current window, then expand/shrink. Turns O(n²) brute force into O(n).', difficulty_rating: 2.0, estimated_hours: 4, prerequisites: ['Arrays - 1D', 'Two Pointers Technique'], reference_url: 'https://www.geeksforgeeks.org/window-sliding-technique/', youtube_search_query: 'Sliding window algorithm', real_world_uses: { examples: [{ company: 'Real-time analytics', use_case: 'Moving average calculation', explanation: 'Window of last 30 days: as new day arrives, remove oldest, add newest. O(1) per update.' }] } },

  // === ADVANCED PHASE 1: DYNAMIC PROGRAMMING ===
  { name: 'Dynamic Programming — 1D', slug: 'dp-1d', tier: 'Advanced', order_in_sequence: 26, simple_definition: 'DP solves overlapping subproblems by storing results (memoization). Instead of computing fib(5) multiple times, compute once and reuse. "Smart recursion with memory."', difficulty_rating: 3.2, estimated_hours: 6, prerequisites: ['Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/dynamic-programming/', youtube_search_query: 'Dynamic programming memoization fibonacci', real_world_uses: { examples: [{ company: 'Compilers', use_case: 'Code optimization', explanation: 'Compilers use DP to find the best instruction order without redundant calculations.' }] } },
  { name: 'Dynamic Programming — 2D', slug: 'dp-2d', tier: 'Advanced', order_in_sequence: 27, simple_definition: '2D DP for 2D problems. Knapsack: given items with weight & value, find max value within capacity. dp[i][w] = max value using first i items with capacity w.', difficulty_rating: 3.5, estimated_hours: 7, prerequisites: ['Dynamic Programming — 1D', '2D Arrays'], reference_url: 'https://www.geeksforgeeks.org/0-1-knapsack-problem/', youtube_search_query: '0/1 knapsack dynamic programming', real_world_uses: { examples: [{ company: 'Logistics', use_case: 'Maximize cargo value within weight limit', explanation: 'Ship has 100-ton capacity. Pack items to maximize value — knapsack problem.' }] } },
  { name: 'Dynamic Programming — String Matching', slug: 'dp-string', tier: 'Advanced', order_in_sequence: 28, simple_definition: 'Longest Common Subsequence (LCS) and Edit Distance find similarity between strings. Used in Git diff, DNA analysis, and spell correction.', difficulty_rating: 3.3, estimated_hours: 6, prerequisites: ['Dynamic Programming — 2D', 'Strings'], reference_url: 'https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/', youtube_search_query: 'Longest common subsequence LCS edit distance', real_world_uses: { examples: [{ company: 'Git', use_case: 'Showing file diffs', explanation: 'Git uses LCS to show which lines changed. LCS finds the longest unchanged portion.' }] } },
  { name: 'Dynamic Programming — Grid Problems', slug: 'dp-grid', tier: 'Advanced', order_in_sequence: 29, simple_definition: 'Path counting and minimum-cost path in a grid. dp[i][j] = answer for reaching cell (i,j). Build from top-left to bottom-right.', difficulty_rating: 3.0, estimated_hours: 5, prerequisites: ['Dynamic Programming — 2D', '2D Arrays'], reference_url: 'https://www.geeksforgeeks.org/count-number-of-paths-in-a-matrix/', youtube_search_query: 'Grid path counting dynamic programming', real_world_uses: { examples: [{ company: 'Robotics', use_case: 'Pathfinding with obstacles', explanation: 'Robot navigating a grid with obstacles. DP finds minimum steps to goal.' }] } },
  { name: 'Dynamic Programming — Advanced', slug: 'dp-advanced', tier: 'Advanced', order_in_sequence: 30, simple_definition: 'Coin change, stock trading, house robber. Recognize overlapping subproblems and identify optimal substructure to apply DP.', difficulty_rating: 3.6, estimated_hours: 7, prerequisites: ['Dynamic Programming — 2D'], reference_url: 'https://www.geeksforgeeks.org/coin-change-dp-7/', youtube_search_query: 'Coin change stock trading house robber DP', real_world_uses: { examples: [{ company: 'Crypto trading bots', use_case: 'Maximize profit with multiple transactions', explanation: 'Given stock prices, find optimal buy/sell days. DP finds the best strategy.' }] } },

  // === ADVANCED PHASE 2: GRAPH ALGORITHMS ===
  { name: 'Strongly Connected Components', slug: 'graph-scc', tier: 'Advanced', order_in_sequence: 31, simple_definition: 'SCCs are maximal groups where every node can reach every other node. Use Tarjan or Kosaraju algorithm.', difficulty_rating: 3.5, estimated_hours: 6, prerequisites: ['Graph Traversal — DFS'], reference_url: 'https://www.geeksforgeeks.org/strongly-connected-components/', youtube_search_query: 'Strongly connected components Tarjan Kosaraju', real_world_uses: { examples: [{ company: 'Compilers', use_case: 'Dead code detection', explanation: 'If code blocks form a cycle but nothing reaches the entry, it is dead code.' }] } },
  { name: 'Minimum Spanning Tree', slug: 'mst', tier: 'Advanced', order_in_sequence: 32, simple_definition: 'MST connects all nodes with minimum total edge weight. Kruskal: sort edges, add if no cycle. Prim: grow tree from one node.', difficulty_rating: 3.3, estimated_hours: 6, prerequisites: ['Graph Basics & Representation', 'Sorting — Merge & Quick Sort'], reference_url: 'https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/', youtube_search_query: 'Kruskal Prim minimum spanning tree algorithm', real_world_uses: { examples: [{ company: 'Telecom', use_case: 'Laying cables with minimum cost', explanation: 'Connect cities with cables. MST finds the minimum total length needed.' }] } },
  { name: 'Topological Sorting', slug: 'topological-sort', tier: 'Advanced', order_in_sequence: 33, simple_definition: 'Linear order of DAG nodes where every edge goes left to right. Use DFS or Kahn\'s algorithm. Used for dependency ordering.', difficulty_rating: 2.8, estimated_hours: 5, prerequisites: ['Graph Traversal — DFS'], reference_url: 'https://www.geeksforgeeks.org/topological-sorting/', youtube_search_query: 'Topological sort DAG directed acyclic graph', real_world_uses: { examples: [{ company: 'Build systems (Make/npm)', use_case: 'Compile files in correct order', explanation: 'File B depends on A. Topological sort ensures A is compiled before B.' }] } },
  { name: 'Bellman-Ford Algorithm', slug: 'bellman-ford', tier: 'Advanced', order_in_sequence: 34, simple_definition: 'Finds shortest path like Dijkstra but handles negative edge weights. O(VE). Also detects negative cycles.', difficulty_rating: 3.2, estimated_hours: 6, prerequisites: ["Dijkstra's Algorithm"], reference_url: 'https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-9/', youtube_search_query: 'Bellman-Ford algorithm negative cycle', real_world_uses: { examples: [{ company: 'Currency exchange systems', use_case: 'Detecting arbitrage opportunities', explanation: 'Negative cycles in currency graphs = infinite money. Bellman-Ford detects it.' }] } },
  { name: 'Floyd-Warshall Algorithm', slug: 'floyd-warshall', tier: 'Advanced', order_in_sequence: 35, simple_definition: 'All-pairs shortest path. Computes shortest distance between every pair of nodes in O(V³). Uses DP.', difficulty_rating: 3.0, estimated_hours: 5, prerequisites: ["Dijkstra's Algorithm"], reference_url: 'https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/', youtube_search_query: 'Floyd-Warshall all-pairs shortest path', real_world_uses: { examples: [{ company: 'Network routing', use_case: 'Knowing all paths in a network', explanation: 'A router needs to know the best path to every other router in the network.' }] } },

  // === ADVANCED PHASE 3: STRING ALGORITHMS ===
  { name: 'Pattern Matching — KMP Algorithm', slug: 'kmp-algorithm', tier: 'Advanced', order_in_sequence: 36, simple_definition: 'Knuth-Morris-Pratt finds a substring in O(n + m) time without backtracking, by precomputing a failure function.', difficulty_rating: 3.3, estimated_hours: 6, prerequisites: ['Strings'], reference_url: 'https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/', youtube_search_query: 'KMP Knuth-Morris-Pratt pattern matching', real_world_uses: { examples: [{ company: 'Text editors', use_case: 'Ctrl+F find functionality', explanation: 'Finding a word in a 10,000-line file. KMP is O(n + m) — instant results.' }] } },
  { name: 'Pattern Matching — Rabin-Karp', slug: 'rabin-karp', tier: 'Advanced', order_in_sequence: 37, simple_definition: 'Uses rolling hash to find a pattern. O(n + m) average. Great for multiple pattern matching.', difficulty_rating: 2.8, estimated_hours: 5, prerequisites: ['Strings', 'Hash Maps / Hash Tables'], reference_url: 'https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/', youtube_search_query: 'Rabin-Karp rolling hash pattern matching', real_world_uses: { examples: [{ company: 'Plagiarism detectors', use_case: 'Finding copied text', explanation: 'Hash patterns from document A and check matches against document B efficiently.' }] } },
  { name: 'Trie Data Structure', slug: 'trie', tier: 'Advanced', order_in_sequence: 38, simple_definition: 'Tree of characters where root-to-leaf paths form words. Perfect for prefix-based searches. Autocomplete in O(m) where m is prefix length.', difficulty_rating: 2.5, estimated_hours: 5, prerequisites: ['Binary Trees Basics', 'Strings'], reference_url: 'https://www.geeksforgeeks.org/trie-insert-and-search/', youtube_search_query: 'Trie prefix tree autocomplete', real_world_uses: { examples: [{ company: 'Google Search', use_case: 'Search autocomplete', explanation: 'Type "dsa", it suggests "dsa tutorial", "dsa course". Trie finds all words starting with "dsa".' }] } },

  // === ADVANCED PHASE 4: ADVANCED TREES ===
  { name: 'AVL Trees', slug: 'avl-trees', tier: 'Advanced', order_in_sequence: 39, simple_definition: 'Self-balancing BST. Height difference between subtrees ≤ 1. Rotations keep tree balanced. Guarantees O(log n) for all operations.', difficulty_rating: 3.8, estimated_hours: 8, prerequisites: ['Binary Search Trees (BST)'], reference_url: 'https://www.geeksforgeeks.org/avl-tree-set-1-insertion/', youtube_search_query: 'AVL tree self-balancing rotation', real_world_uses: { examples: [{ company: 'Databases', use_case: 'Balanced indexing', explanation: 'AVL trees keep indexes balanced so lookup stays O(log n) even as data grows.' }] } },
  { name: 'Segment Trees', slug: 'segment-trees', tier: 'Advanced', order_in_sequence: 40, simple_definition: 'Binary tree storing range aggregates. Query any range in O(log n) and update in O(log n). Handles range min/max/sum with point updates.', difficulty_rating: 3.7, estimated_hours: 7, prerequisites: ['Binary Trees Basics', 'Recursion Basics'], reference_url: 'https://www.geeksforgeeks.org/segment-tree-set-1-sum-of-given-range/', youtube_search_query: 'Segment tree range query update', real_world_uses: { examples: [{ company: 'Competitive programming', use_case: 'Range sum with point updates', explanation: 'Query range sum + update a value — both O(log n) with segment tree.' }] } },
  { name: 'Fenwick Tree', slug: 'fenwick-tree', tier: 'Advanced', order_in_sequence: 41, simple_definition: 'Compact range-sum structure using binary representation. O(log n) query and update with O(n) space. Simpler to code than segment trees.', difficulty_rating: 3.5, estimated_hours: 6, prerequisites: ['Binary Trees Basics', 'Bit Manipulation'], reference_url: 'https://www.geeksforgeeks.org/binary-indexed-tree-or-fenwick-tree/', youtube_search_query: 'Fenwick tree binary indexed tree', real_world_uses: { examples: [{ company: 'Competitive programming', use_case: 'Efficient prefix sum with updates', explanation: 'Update values and query prefix sums — both O(log n).' }] } },

  // === ADVANCED PHASE 5: ADVANCED TECHNIQUES ===
  { name: 'Greedy Algorithms', slug: 'greedy-algorithms', tier: 'Advanced', order_in_sequence: 42, simple_definition: 'Make the locally optimal choice at each step. Greedy works when local optimum leads to global optimum. Used in interval scheduling, Huffman coding, and MST.', difficulty_rating: 2.8, estimated_hours: 5, prerequisites: ['Sorting — Merge & Quick Sort'], reference_url: 'https://www.geeksforgeeks.org/greedy-algorithms/', youtube_search_query: 'Greedy algorithm activity selection', real_world_uses: { examples: [{ company: 'Compression software (zip)', use_case: 'Huffman coding', explanation: 'Greedy assigns short codes to frequent characters. Minimizes compressed file size.' }] } },
  { name: 'Backtracking', slug: 'backtracking', tier: 'Advanced', order_in_sequence: 43, simple_definition: 'Build a solution incrementally, abandoning a path as soon as it violates constraints. Used for N-Queens, Sudoku, and generating permutations.', difficulty_rating: 3.0, estimated_hours: 6, prerequisites: ['Recursion Basics', 'Graph Traversal — DFS'], reference_url: 'https://www.geeksforgeeks.org/backtracking-algorithms/', youtube_search_query: 'Backtracking N-queens sudoku solver', real_world_uses: { examples: [{ company: 'Sudoku solvers', use_case: 'Finding a valid solution', explanation: 'Try a digit, check constraints; if invalid, backtrack and try the next digit.' }] } },
  { name: 'Disjoint Set Union (DSU)', slug: 'disjoint-set-union', tier: 'Advanced', order_in_sequence: 44, simple_definition: 'Efficiently find connected components and detect cycles. Union-Find with path compression gives near O(1) operations — O(α(n)) amortized.', difficulty_rating: 2.5, estimated_hours: 5, prerequisites: ['Graph Basics & Representation'], reference_url: 'https://www.geeksforgeeks.org/union-find/', youtube_search_query: 'Union-Find DSU disjoint set', real_world_uses: { examples: [{ company: 'Social networks', use_case: 'Finding friend groups', explanation: 'DSU connects friend clusters. "Are X and Y in the same group?" answered in near O(1).' }] } },
  { name: 'Bit Manipulation', slug: 'bit-manipulation', tier: 'Advanced', order_in_sequence: 45, simple_definition: 'Operations on individual bits. XOR finds unique elements, AND checks powers of 2, bit shifting multiplies/divides. Often replaces expensive arithmetic.', difficulty_rating: 2.0, estimated_hours: 4, prerequisites: ['Arrays - 1D'], reference_url: 'https://www.geeksforgeeks.org/bit-manipulation-important-tricks/', youtube_search_query: 'Bit manipulation XOR AND OR shift', real_world_uses: { examples: [{ company: 'Embedded systems', use_case: 'Hardware register control', explanation: 'Set/clear/toggle specific bits to control hardware pins and peripheral features.' }] } },

  // === ADVANCED PHASE 6: COMPETITIVE PROGRAMMING ===
  { name: 'Modular Arithmetic', slug: 'modular-arithmetic', tier: 'Advanced', order_in_sequence: 46, simple_definition: 'Handle huge numbers with modulo to prevent overflow. Compute permutations, combinations, and power modulo a prime. Essential for competitive programming.', difficulty_rating: 3.3, estimated_hours: 6, prerequisites: ['Bit Manipulation'], reference_url: 'https://www.geeksforgeeks.org/modular-arithmetic/', youtube_search_query: 'Modular arithmetic modulo combinatorics', real_world_uses: { examples: [{ company: 'Competitive programming', use_case: 'Computing nCr mod 10^9+7', explanation: 'Compute combinations on huge numbers without overflow using modular arithmetic.' }] } },
  { name: 'Problem-Solving Patterns', slug: 'problem-solving-patterns', tier: 'Advanced', order_in_sequence: 47, simple_definition: 'Recognize common patterns — sliding window, two pointers, DP, greedy, divide & conquer. Identifying the pattern gives you the algorithm instantly.', difficulty_rating: 2.5, estimated_hours: 8, prerequisites: ['Sliding Window', 'Two Pointers Technique'], reference_url: 'https://www.geeksforgeeks.org/must-do-coding-questions-for-companies-like-amazon-microsoft-adobe/', youtube_search_query: 'Coding interview patterns two pointer DP', real_world_uses: { examples: [{ company: 'Tech interviews (FAANG)', use_case: 'Problem recognition framework', explanation: 'Recognize the pattern → instant algorithm. Sliding window? Two pointers? DP? Makes interviews much easier.' }] } },
];

const promptTemplates = [
  { difficulty: 'easy', focus_area: 'Basics & traversal', template_text: 'I am learning {{topic}}. Give me 3 easy LeetCode questions that test fundamental understanding of {{topic}}. For each question:\n1. State the problem clearly\n2. Give an example input and expected output\n3. Mention what concept it tests\n\nDo NOT give hints or solutions yet.' },
  { difficulty: 'medium', focus_area: 'Pattern recognition', template_text: 'I am practicing {{topic}} and I understand the basics. Give me 3 medium-difficulty LeetCode questions involving common patterns with {{topic}}. For each question:\n1. State the problem clearly\n2. Give an example input and expected output\n3. Mention the key insight or pattern needed\n\nDo NOT give hints or solutions yet.' },
  { difficulty: 'hard', focus_area: 'Optimization & edge cases', template_text: 'I am confident in {{topic}} and want a real challenge. Give me 2 hard LeetCode questions involving {{topic}} that require optimization, edge-case handling, or combining multiple concepts. For each:\n1. State the problem clearly\n2. Give an example input and expected output\n3. Mention what makes it hard\n\nDo NOT give hints or solutions yet.' },
];

async function seed() {
  const client = await pool.connect();
  try {
    logger.info('Seeding 47 comprehensive DSA topics...');
    let inserted = 0;

    for (const topic of topics) {
      const { rows } = await client.query(
        `INSERT INTO topics
           (name, slug, tier, simple_definition, real_world_uses, prerequisites,
            order_in_sequence, difficulty_rating, estimated_hours,
            youtube_search_query, reference_url)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
         ON CONFLICT (slug) DO UPDATE SET
           name = EXCLUDED.name,
           tier = EXCLUDED.tier,
           simple_definition = EXCLUDED.simple_definition,
           real_world_uses = EXCLUDED.real_world_uses,
           prerequisites = EXCLUDED.prerequisites,
           order_in_sequence = EXCLUDED.order_in_sequence,
           difficulty_rating = EXCLUDED.difficulty_rating,
           estimated_hours = EXCLUDED.estimated_hours,
           youtube_search_query = EXCLUDED.youtube_search_query,
           reference_url = EXCLUDED.reference_url,
           updated_at = NOW()
         RETURNING id, name`,
        [
          topic.name, topic.slug, topic.tier,
          topic.simple_definition,
          JSON.stringify(topic.real_world_uses),
          JSON.stringify(topic.prerequisites),
          topic.order_in_sequence, topic.difficulty_rating, topic.estimated_hours,
          topic.youtube_search_query, topic.reference_url,
        ]
      );

      const topicId = rows[0].id;

      await client.query('DELETE FROM prompt_templates WHERE topic_id = $1', [topicId]);

      for (const pt of promptTemplates) {
        await client.query(
          `INSERT INTO prompt_templates (topic_id, difficulty, template_text, focus_area)
           VALUES ($1,$2,$3,$4)`,
          [topicId, pt.difficulty, pt.template_text.replace(/\{\{topic\}\}/g, topic.name), pt.focus_area]
        );
      }

      logger.info(`  ✓ ${topic.name}`);
      inserted++;
    }

    logger.info(`Seeding complete! ${inserted} topics inserted/updated.`);
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch((err) => {
  logger.error({ err }, 'Seed failed');
  process.exit(1);
});
